ci: include job to test on Cygwin

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -378,7 +378,96 @@ jobs:
 
       - name: Set environment variable to hold the rockspec name
         run: |
-          if test $GITHUB_REF_TYPE" = "tag"; then
+          if test "$GITHUB_REF_TYPE" = "tag"; then
+            echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
+          else
+            echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
+          fi
+
+      - name: Lint
+        run: luarocks lint "$ROCKSPEC"
+
+      - name: Build
+        run: luarocks make "$ROCKSPEC"
+
+      - name: Test
+        run: |
+          for f in samples/*.lua; do
+            echo "Running sample: ${f}";
+
+            lua "${f}" || {
+              echo "Failed to run the sample: ${f}";
+              exit 1;
+            }
+          done
+
+  test-cygwin:
+    runs-on: windows-latest
+
+    defaults:
+      run:
+        shell: D:\cygwin\bin\bash.exe --login -eo pipefail -o igncr '{0}'
+
+    env:
+      CYGWIN_NOWINPATH: 1
+      CHERE_INVOKING: 1
+
+    steps:
+
+      - name: Change autocrlf to input
+        shell: cmd
+        run: git config --global core.autocrlf input
+
+      - name: Checkout
+        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
+
+      - name: Setup Cygwin
+        uses: cygwin/cygwin-install-action@3f0a3f9f988f7e96b8c18098ae05eaec175f5b52 # v6
+        with:
+          platform: x86_64
+          packages: |
+            coreutils
+            wget
+            gcc-g++
+            make
+            lua
+            liblua-devel
+            unzip
+            libuuid-devel
+
+      - name: Setup LuaRocks
+        run: |
+          luarocks_version="3.13.0"
+          luarocks_url="https://luarocks.github.io/luarocks/releases/luarocks-${luarocks_version}.tar.gz"
+
+          wget -P/tmp "${luarocks_url}" || {
+            echo "Failed to download LuaRocks ${luarocks_version}";
+            exit 1;
+          }
+
+          tar -C /tmp -xf "/tmp/luarocks-${luarocks_version}.tar.gz" || {
+            echo "Failed to extract LuaRocks ${luarocks_version}";
+            exit 1;
+          }
+
+          cd "/tmp/luarocks-${luarocks_version}" && \
+          sed \
+            -e "s|SHEBANG = .*|SHEBANG = \\\#\!/bin/env lua|" \
+            -i GNUmakefile || {
+            echo "Failed to patch GNUmakefile";
+            exit 1;
+          }
+
+          ./configure --prefix=/usr && make && make install || {
+            echo "Failed to configure, build or install LuaRocks ${luarocks_version}";
+            exit 1;
+          }
+
+          echo 'eval $(luarocks path)' >> /etc/profile.d/luarocks.sh
+
+      - name: Set environment variable to hold the rockspec name
+        run: |
+          if test "$GITHUB_REF_TYPE" = "tag"; then
             echo "ROCKSPEC=$(make -f Makefile.unix echo-rockspec)" >> $GITHUB_ENV
           else
             echo "ROCKSPEC=$(make -f Makefile.unix echo-dev-rockspec)" >> $GITHUB_ENV
